alias aliases='nvim ~/.bash_aliases'
alias r='ranger_cd'
alias suwofi='sudo wofi -show run'
alias sdn='shutdown now'
alias sps='sudo pacman -Syu'
alias init='nvim ~/.config/nvim/init.vim'
alias yt='mpv --ytdl-format=22'
alias fight='sh ~/Fightcade/Fightcade2.sh'
