alias aliases='nvim ~/.bash_aliases'
alias r='ranger_cd'
alias suwofi='sudo wofi -show run'
alias sdn='shutdown now'
alias sdr='shutdown -r now'
alias sps='sudo pacman -Syu'
alias init='nvim ~/.config/nvim/init.vim'
alias yt='mpv --ytdl-format=22'
alias fight='sh ~/Fightcade/Fightcade2.sh'
alias ll='ls -l'
alias la='ls -la'
alias gs='git status'
alias gp='git push'
alias gpl='git pull'
alias gl='git log'
